// lib/models/mood_model.dart
import 'package:flutter/material.dart';
import 'content_object.dart';

enum MoodQuadrant { red, yellow, green, blue }

enum MoodSource { system, user }

class MoodDefinition extends ContentObject {
  final String label;
  final String emoji;
  final String color;
  final MoodSource source;
  final bool hidden;
  final String? labelEn;
  final String? description;
  final MoodQuadrant quadrant;
  final int pleasantness;
  final int energy;

  int get numericValue => pleasantness;

  MoodDefinition({
    super.id,
    String? title,
    required this.label,
    required this.emoji,
    required this.color,
    super.order,
    this.source = MoodSource.system,
    this.hidden = false,
    this.labelEn,
    this.description,
    int? pleasantness,
    int? energy,
    MoodQuadrant? quadrant,
    int? numericValue,
    super.aliases,
    super.obsidianPath,
  }) : pleasantness = pleasantness ?? numericValue ?? 3,
       energy = energy ?? 3,
       quadrant =
           quadrant ??
           _quadrantFromCoordinates(energy ?? 3, pleasantness ?? numericValue ?? 3),
       super(title: title ?? label);

  static MoodQuadrant _quadrantFromCoordinates(int energy, int pleasantness) {
    if (energy >= 5 && pleasantness >= 5) return MoodQuadrant.yellow;
    if (energy >= 5 && pleasantness < 5) return MoodQuadrant.red;
    if (energy < 5 && pleasantness >= 5) return MoodQuadrant.green;
    return MoodQuadrant.blue;
  }

  MoodDefinition copyWith({
    String? id,
    String? title,
    String? label,
    String? emoji,
    String? color,
    int? order,
    MoodSource? source,
    bool? hidden,
    String? labelEn,
    String? description,
    MoodQuadrant? quadrant,
    int? pleasantness,
    int? energy,
    List<String>? aliases,
    String? obsidianPath,
  }) {
    final copy = MoodDefinition(
      id: id ?? this.id,
      title: title ?? this.title,
      label: label ?? this.label,
      emoji: emoji ?? this.emoji,
      color: color ?? this.color,
      order: order ?? this.order,
      source: source ?? this.source,
      hidden: hidden ?? this.hidden,
      labelEn: labelEn ?? this.labelEn,
      description: description ?? this.description,
      quadrant: quadrant ?? this.quadrant,
      pleasantness: pleasantness ?? this.pleasantness,
      energy: energy ?? this.energy,
      aliases: aliases ?? this.aliases,
      obsidianPath: obsidianPath ?? this.obsidianPath,
    );
    copy.loadBaseMap(toBaseMap());
    return copy;
  }

  @override
  String get type => 'mood_definition';

  @override
  bool get isIncomplete => label.trim().isEmpty || emoji.trim().isEmpty;

  @override
  String get slug => id;

  @override
  String toMarkdown() {
    final frontmatter = toBaseMap();
    frontmatter['source'] = source.name;
    frontmatter['hidden'] = hidden;
    frontmatter['label'] = label;
    if (labelEn != null) frontmatter['label_en'] = labelEn;
    if (description != null) frontmatter['description'] = description;
    frontmatter['emoji'] = emoji;
    frontmatter['quadrant'] = quadrant.name;
    frontmatter['pleasantness'] = pleasantness;
    frontmatter['energy'] = energy;
    frontmatter['color'] = color;
    return generateMarkdown(frontmatter, description ?? '');
  }

  factory MoodDefinition.fromMarkdown(
    Map<String, dynamic> frontmatter,
    String body,
  ) {
    final mood = MoodDefinition(
      id: frontmatter['id'] as String? ?? 'neutral',
      title: frontmatter['title'] as String? ?? 'Neutral',
      label: frontmatter['label'] as String? ?? 'Neutral',
      emoji: frontmatter['emoji'] as String? ?? '😐',
      color: frontmatter['color'] as String? ?? '#9E9E9E',
      order: (frontmatter['order'] as num? ?? 3).toInt(),
      source: MoodSource.values.firstWhere(
        (e) => e.name == frontmatter['source']?.toString(),
        orElse: () => MoodSource.system,
      ),
      hidden: frontmatter['hidden'] == true,
      labelEn: frontmatter['label_en'] as String?,
      description: frontmatter['description'] as String? ?? body.trim(),
      quadrant: MoodQuadrant.values.firstWhere(
        (q) => q.name == frontmatter['quadrant']?.toString(),
        orElse: () => MoodQuadrant.blue,
      ),
      pleasantness: (frontmatter['pleasantness'] as num? ?? 3).toInt(),
      energy: (frontmatter['energy'] as num? ?? 3).toInt(),
      aliases: List<String>.from(frontmatter['aliases'] ?? []),
    );
    mood.loadBaseMap(frontmatter);
    return mood;
  }

  static Color quadrantColor(MoodQuadrant q) => switch (q) {
    MoodQuadrant.red => const Color(0xFFEF5350),
    MoodQuadrant.yellow => const Color(0xFFFFA726),
    MoodQuadrant.green => const Color(0xFF66BB6A),
    MoodQuadrant.blue => const Color(0xFF42A5F5),
  };

  static const Map<String, String> _systemMoodDescriptions = {
    // YELLOW quadrant (20 moods)
    'pleasant': 'A light, easy sense that things are going fine.',
    'cheerful': 'Bright and good-humored, ready to smile.',
    'hopeful': 'Looking forward to something getting better.',
    'focused': 'Locked in, clear-headed, and on task.',
    'optimistic': 'Expecting things to work out well.',
    'happy': 'A solid, warm sense of things being good.',
    'lively': 'Full of spark, hard to sit still.',
    'playful': 'In the mood to joke around and have fun.',
    'proud': 'Satisfied with something you did or achieved.',
    'upbeat': 'Bouncy, positive energy that\'s easy to spot.',
    'excited': 'Buzzing about something coming up or happening now.',
    'festive': 'Celebratory, in a party-like state of mind.',
    'energized': 'Full of physical and mental drive to go.',
    'motivated': 'Pulled strongly toward doing something.',
    'enthusiastic': 'Eager and vocal about something you care about.',
    'thrilled': 'A rush of intense, almost overwhelming excitement.',
    'inspired': 'Struck by an idea or possibility, wanting to act on it.',
    'amazed': 'Caught off guard by something wonderful.',
    'elated': 'Riding a high, almost giddy with joy.',
    'joyful': 'Deep, unmistakable happiness, hard to contain.',
    // RED quadrant (20 moods)
    'peeved': 'Mildly annoyed by something small.',
    'annoyed': 'Irritated by something that\'s bothering you.',
    'worried': 'Uneasy about something that might go wrong.',
    'nervous': 'On edge about something coming up.',
    'troubled': 'Weighed down by a concern you can\'t shake.',
    'irritated': 'Actively bothered, patience running thin.',
    'tense': 'Wound up, body and mind both on alert.',
    'agitated': 'Restless and stirred up, hard to settle.',
    'jittery': 'Shaky, keyed-up energy you can\'t quite place.',
    'stressed': 'Under pressure, feeling like too much at once.',
    'anxious': 'Gripped by worry that\'s hard to set aside.',
    'frustrated': 'Blocked from something you\'re trying to do.',
    'overwhelmed': 'Facing more than you feel able to handle right now.',
    'alarmed': 'Suddenly on high alert to a possible threat.',
    'frightened': 'Afraid of something happening or about to happen.',
    'angry': 'Strong displeasure, often at something unfair.',
    'furious': 'Intense anger, close to boiling over.',
    'enraged': 'Anger at its peak, hard to contain.',
    'panicked': 'Sudden, overpowering fear pushing you to act now.',
    'shocked': 'Jolted by something unexpected and unwelcome.',
    // GREEN quadrant (20 moods)
    'thoughtful': 'Quietly turning something over in your mind.',
    'mellow': 'Easygoing, nothing pushing at you right now.',
    'comfy': 'Physically and mentally settled in.',
    'cozy': 'Warm, sheltered, small-scale contentment.',
    'balanced': 'Steady, nothing pulling you too far one way.',
    'calm': 'Quiet inside, no urgency to move or react.',
    'relaxed': 'Muscles and mind both loosened up.',
    'easygoing': 'Unbothered, taking things as they come.',
    'content': 'Quietly satisfied with how things are right now.',
    'carefree': 'Light, unburdened by worry for the moment.',
    'at_ease': 'Fully settled, nothing on guard.',
    'restful': 'Recovering, replenished, in no rush.',
    'grateful': 'Aware of and warmed by something good you have.',
    'satisfied': 'A quiet sense that something turned out well.',
    'secure': 'Steady and safe, nothing shaky underfoot.',
    'serene': 'Deep stillness, untouched by outside noise.',
    'peaceful': 'A settled quiet, inside and out.',
    'tranquil': 'Calm that runs deep, almost still-water quiet.',
    'blessed': 'A quiet fullness, aware of your good fortune.',
    'loving': 'Warm, open, full of affection toward someone.',
    // BLUE quadrant (20 moods)
    'bored': 'Understimulated, waiting for something to change.',
    'tired': 'Low on physical or mental fuel.',
    'uneasy': 'A vague sense that something\'s not quite right.',
    'disappointed': 'Let down by something that didn\'t go as hoped.',
    'weary': 'Worn down after sustained effort.',
    'down': 'Low mood, nothing dramatic, just heavier than usual.',
    'gloomy': 'A dim, grey mood hanging over things.',
    'discouraged': 'Losing motivation after a setback.',
    'lonely': 'Missing connection you don\'t currently have.',
    'exhausted': 'Completely drained, past ordinary tiredness.',
    'sad': 'A heavy, low feeling, often tied to a loss.',
    'disheartened': 'Deflated, hope knocked down a notch.',
    'drained': 'Emptied out, little left to give right now.',
    'apathetic': 'Detached, hard to care about much right now.',
    'alienated': 'Cut off or distant from people around you.',
    'miserable': 'A deep, all-over unpleasant state.',
    'depressed': 'A heavy, persistent low that colors everything.',
    'hopeless': 'Feeling like nothing will improve.',
    'despondent': 'Low and discouraged, with little energy to resist it.',
    'despair': 'The deepest, most depleted end of this quadrant.',
  };

  static List<MoodDefinition> get systemMoods =>
      [
            // YELLOW quadrant (20 moods) - high energy, pleasant
            MoodDefinition(
              id: 'pleasant',
              source: MoodSource.system,
              label: 'Pleasant',
              labelEn: 'Pleasant',
              emoji: '🙂',
              quadrant: MoodQuadrant.yellow,
              pleasantness: 6,
              energy: 6,
              color: '#FFA726',
              order: 1,
              aliases: ['pleasant'],
            ),
            MoodDefinition(
              id: 'cheerful',
              source: MoodSource.system,
              label: 'Cheerful',
              labelEn: 'Cheerful',
              emoji: '😊',
              quadrant: MoodQuadrant.yellow,
              pleasantness: 7,
              energy: 6,
              color: '#FFA726',
              order: 2,
              aliases: ['cheerful'],
            ),
            MoodDefinition(
              id: 'hopeful',
              source: MoodSource.system,
              label: 'Hopeful',
              labelEn: 'Hopeful',
              emoji: '🌱',
              quadrant: MoodQuadrant.yellow,
              pleasantness: 6,
              energy: 6,
              color: '#FFA726',
              order: 3,
              aliases: ['hopeful'],
            ),
            MoodDefinition(
              id: 'focused',
              source: MoodSource.system,
              label: 'Focused',
              labelEn: 'Focused',
              emoji: '🎯',
              quadrant: MoodQuadrant.yellow,
              pleasantness: 6,
              energy: 6,
              color: '#FFA726',
              order: 4,
              aliases: ['focused'],
            ),
            MoodDefinition(
              id: 'optimistic',
              source: MoodSource.system,
              label: 'Optimistic',
              labelEn: 'Optimistic',
              emoji: '☀️',
              quadrant: MoodQuadrant.yellow,
              pleasantness: 7,
              energy: 6,
              color: '#FFA726',
              order: 5,
              aliases: ['optimistic'],
            ),
            MoodDefinition(
              id: 'happy',
              source: MoodSource.system,
              label: 'Happy',
              labelEn: 'Happy',
              emoji: '😄',
              quadrant: MoodQuadrant.yellow,
              pleasantness: 7,
              energy: 7,
              color: '#FFA726',
              order: 6,
              aliases: ['happy'],
            ),
            MoodDefinition(
              id: 'lively',
              source: MoodSource.system,
              label: 'Lively',
              labelEn: 'Lively',
              emoji: '✨',
              quadrant: MoodQuadrant.yellow,
              pleasantness: 7,
              energy: 7,
              color: '#FFA726',
              order: 7,
              aliases: ['lively'],
            ),
            MoodDefinition(
              id: 'playful',
              source: MoodSource.system,
              label: 'Playful',
              labelEn: 'Playful',
              emoji: '🤸',
              quadrant: MoodQuadrant.yellow,
              pleasantness: 7,
              energy: 7,
              color: '#FFA726',
              order: 8,
              aliases: ['playful'],
            ),
            MoodDefinition(
              id: 'proud',
              source: MoodSource.system,
              label: 'Proud',
              labelEn: 'Proud',
              emoji: '🦁',
              quadrant: MoodQuadrant.yellow,
              pleasantness: 7,
              energy: 7,
              color: '#FFA726',
              order: 9,
              aliases: ['proud'],
            ),
            MoodDefinition(
              id: 'upbeat',
              source: MoodSource.system,
              label: 'Upbeat',
              labelEn: 'Upbeat',
              emoji: '🎶',
              quadrant: MoodQuadrant.yellow,
              pleasantness: 8,
              energy: 7,
              color: '#FFA726',
              order: 10,
              aliases: ['upbeat'],
            ),
            MoodDefinition(
              id: 'excited',
              source: MoodSource.system,
              label: 'Excited',
              labelEn: 'Excited',
              emoji: '🤩',
              quadrant: MoodQuadrant.yellow,
              pleasantness: 8,
              energy: 8,
              color: '#FFA726',
              order: 11,
              aliases: ['excited'],
            ),
            MoodDefinition(
              id: 'festive',
              source: MoodSource.system,
              label: 'Festive',
              labelEn: 'Festive',
              emoji: '🎉',
              quadrant: MoodQuadrant.yellow,
              pleasantness: 8,
              energy: 8,
              color: '#FFA726',
              order: 12,
              aliases: ['festive'],
            ),
            MoodDefinition(
              id: 'energized',
              source: MoodSource.system,
              label: 'Energized',
              labelEn: 'Energized',
              emoji: '⚡',
              quadrant: MoodQuadrant.yellow,
              pleasantness: 8,
              energy: 8,
              color: '#FFA726',
              order: 13,
              aliases: ['energized'],
            ),
            MoodDefinition(
              id: 'motivated',
              source: MoodSource.system,
              label: 'Motivated',
              labelEn: 'Motivated',
              emoji: '🚀',
              quadrant: MoodQuadrant.yellow,
              pleasantness: 8,
              energy: 8,
              color: '#FFA726',
              order: 14,
              aliases: ['motivated'],
            ),
            MoodDefinition(
              id: 'enthusiastic',
              source: MoodSource.system,
              label: 'Enthusiastic',
              labelEn: 'Enthusiastic',
              emoji: '🙌',
              quadrant: MoodQuadrant.yellow,
              pleasantness: 9,
              energy: 8,
              color: '#FFA726',
              order: 15,
              aliases: ['enthusiastic'],
            ),
            MoodDefinition(
              id: 'thrilled',
              source: MoodSource.system,
              label: 'Thrilled',
              labelEn: 'Thrilled',
              emoji: '🎢',
              quadrant: MoodQuadrant.yellow,
              pleasantness: 9,
              energy: 9,
              color: '#FFA726',
              order: 16,
              aliases: ['thrilled'],
            ),
            MoodDefinition(
              id: 'inspired',
              source: MoodSource.system,
              label: 'Inspired',
              labelEn: 'Inspired',
              emoji: '💡',
              quadrant: MoodQuadrant.yellow,
              pleasantness: 9,
              energy: 9,
              color: '#FFA726',
              order: 17,
              aliases: ['inspired'],
            ),
            MoodDefinition(
              id: 'amazed',
              source: MoodSource.system,
              label: 'Amazed',
              labelEn: 'Amazed',
              emoji: '😲',
              quadrant: MoodQuadrant.yellow,
              pleasantness: 9,
              energy: 9,
              color: '#FFA726',
              order: 18,
              aliases: ['amazed'],
            ),
            MoodDefinition(
              id: 'elated',
              source: MoodSource.system,
              label: 'Elated',
              labelEn: 'Elated',
              emoji: '🥳',
              quadrant: MoodQuadrant.yellow,
              pleasantness: 9,
              energy: 10,
              color: '#FFA726',
              order: 19,
              aliases: ['elated'],
            ),
            MoodDefinition(
              id: 'joyful',
              source: MoodSource.system,
              label: 'Joyful',
              labelEn: 'Joyful',
              emoji: '😁',
              quadrant: MoodQuadrant.yellow,
              pleasantness: 10,
              energy: 9,
              color: '#FFA726',
              order: 20,
              aliases: ['joyful'],
            ),
            // RED quadrant (20 moods) - high energy, unpleasant
            MoodDefinition(
              id: 'peeved',
              source: MoodSource.system,
              label: 'Peeved',
              labelEn: 'Peeved',
              emoji: '😒',
              quadrant: MoodQuadrant.red,
              pleasantness: 4,
              energy: 6,
              color: '#EF5350',
              order: 21,
              aliases: ['peeved'],
            ),
            MoodDefinition(
              id: 'annoyed',
              source: MoodSource.system,
              label: 'Annoyed',
              labelEn: 'Annoyed',
              emoji: '😑',
              quadrant: MoodQuadrant.red,
              pleasantness: 4,
              energy: 6,
              color: '#EF5350',
              order: 22,
              aliases: ['annoyed'],
            ),
            MoodDefinition(
              id: 'worried',
              source: MoodSource.system,
              label: 'Worried',
              labelEn: 'Worried',
              emoji: '😟',
              quadrant: MoodQuadrant.red,
              pleasantness: 4,
              energy: 6,
              color: '#EF5350',
              order: 23,
              aliases: ['worried'],
            ),
            MoodDefinition(
              id: 'nervous',
              source: MoodSource.system,
              label: 'Nervous',
              labelEn: 'Nervous',
              emoji: '😬',
              quadrant: MoodQuadrant.red,
              pleasantness: 4,
              energy: 6,
              color: '#EF5350',
              order: 24,
              aliases: ['nervous'],
            ),
            MoodDefinition(
              id: 'troubled',
              source: MoodSource.system,
              label: 'Troubled',
              labelEn: 'Troubled',
              emoji: '😔',
              quadrant: MoodQuadrant.red,
              pleasantness: 4,
              energy: 6,
              color: '#EF5350',
              order: 25,
              aliases: ['troubled'],
            ),
            MoodDefinition(
              id: 'irritated',
              source: MoodSource.system,
              label: 'Irritated',
              labelEn: 'Irritated',
              emoji: '😠',
              quadrant: MoodQuadrant.red,
              pleasantness: 3,
              energy: 7,
              color: '#EF5350',
              order: 26,
              aliases: ['irritated'],
            ),
            MoodDefinition(
              id: 'tense',
              source: MoodSource.system,
              label: 'Tense',
              labelEn: 'Tense',
              emoji: '😖',
              quadrant: MoodQuadrant.red,
              pleasantness: 3,
              energy: 7,
              color: '#EF5350',
              order: 27,
              aliases: ['tense'],
            ),
            MoodDefinition(
              id: 'agitated',
              source: MoodSource.system,
              label: 'Agitated',
              labelEn: 'Agitated',
              emoji: '😤',
              quadrant: MoodQuadrant.red,
              pleasantness: 3,
              energy: 7,
              color: '#EF5350',
              order: 28,
              aliases: ['agitated'],
            ),
            MoodDefinition(
              id: 'jittery',
              source: MoodSource.system,
              label: 'Jittery',
              labelEn: 'Jittery',
              emoji: '😰',
              quadrant: MoodQuadrant.red,
              pleasantness: 3,
              energy: 7,
              color: '#EF5350',
              order: 29,
              aliases: ['jittery'],
            ),
            MoodDefinition(
              id: 'stressed',
              source: MoodSource.system,
              label: 'Stressed',
              labelEn: 'Stressed',
              emoji: '🥵',
              quadrant: MoodQuadrant.red,
              pleasantness: 3,
              energy: 7,
              color: '#EF5350',
              order: 30,
              aliases: ['stressed'],
            ),
            MoodDefinition(
              id: 'anxious',
              source: MoodSource.system,
              label: 'Anxious',
              labelEn: 'Anxious',
              emoji: '😨',
              quadrant: MoodQuadrant.red,
              pleasantness: 2,
              energy: 8,
              color: '#EF5350',
              order: 31,
              aliases: ['anxious'],
            ),
            MoodDefinition(
              id: 'frustrated',
              source: MoodSource.system,
              label: 'Frustrated',
              labelEn: 'Frustrated',
              emoji: '😣',
              quadrant: MoodQuadrant.red,
              pleasantness: 2,
              energy: 8,
              color: '#EF5350',
              order: 32,
              aliases: ['frustrated'],
            ),
            MoodDefinition(
              id: 'overwhelmed',
              source: MoodSource.system,
              label: 'Overwhelmed',
              labelEn: 'Overwhelmed',
              emoji: '🌀',
              quadrant: MoodQuadrant.red,
              pleasantness: 2,
              energy: 8,
              color: '#EF5350',
              order: 33,
              aliases: ['overwhelmed'],
            ),
            MoodDefinition(
              id: 'alarmed',
              source: MoodSource.system,
              label: 'Alarmed',
              labelEn: 'Alarmed',
              emoji: '🚨',
              quadrant: MoodQuadrant.red,
              pleasantness: 2,
              energy: 8,
              color: '#EF5350',
              order: 34,
              aliases: ['alarmed'],
            ),
            MoodDefinition(
              id: 'frightened',
              source: MoodSource.system,
              label: 'Frightened',
              labelEn: 'Frightened',
              emoji: '😧',
              quadrant: MoodQuadrant.red,
              pleasantness: 2,
              energy: 8,
              color: '#EF5350',
              order: 35,
              aliases: ['frightened'],
            ),
            MoodDefinition(
              id: 'angry',
              source: MoodSource.system,
              label: 'Angry',
              labelEn: 'Angry',
              emoji: '😡',
              quadrant: MoodQuadrant.red,
              pleasantness: 1,
              energy: 9,
              color: '#EF5350',
              order: 36,
              aliases: ['angry'],
            ),
            MoodDefinition(
              id: 'furious',
              source: MoodSource.system,
              label: 'Furious',
              labelEn: 'Furious',
              emoji: '🤬',
              quadrant: MoodQuadrant.red,
              pleasantness: 1,
              energy: 10,
              color: '#EF5350',
              order: 37,
              aliases: ['furious'],
            ),
            MoodDefinition(
              id: 'enraged',
              source: MoodSource.system,
              label: 'Enraged',
              labelEn: 'Enraged',
              emoji: '🔥',
              quadrant: MoodQuadrant.red,
              pleasantness: 0,
              energy: 10,
              color: '#EF5350',
              order: 38,
              aliases: ['enraged'],
            ),
            MoodDefinition(
              id: 'panicked',
              source: MoodSource.system,
              label: 'Panicked',
              labelEn: 'Panicked',
              emoji: '😱',
              quadrant: MoodQuadrant.red,
              pleasantness: 1,
              energy: 10,
              color: '#EF5350',
              order: 39,
              aliases: ['panicked'],
            ),
            MoodDefinition(
              id: 'shocked',
              source: MoodSource.system,
              label: 'Shocked',
              labelEn: 'Shocked',
              emoji: '😳',
              quadrant: MoodQuadrant.red,
              pleasantness: 1,
              energy: 9,
              color: '#EF5350',
              order: 40,
              aliases: ['shocked'],
            ),
            // GREEN quadrant (20 moods) - low energy, pleasant
            MoodDefinition(
              id: 'thoughtful',
              source: MoodSource.system,
              label: 'Thoughtful',
              labelEn: 'Thoughtful',
              emoji: '🤔',
              quadrant: MoodQuadrant.green,
              pleasantness: 6,
              energy: 4,
              color: '#66BB6A',
              order: 41,
              aliases: ['thoughtful'],
            ),
            MoodDefinition(
              id: 'mellow',
              source: MoodSource.system,
              label: 'Mellow',
              labelEn: 'Mellow',
              emoji: '🎐',
              quadrant: MoodQuadrant.green,
              pleasantness: 6,
              energy: 4,
              color: '#66BB6A',
              order: 42,
              aliases: ['mellow'],
            ),
            MoodDefinition(
              id: 'comfy',
              source: MoodSource.system,
              label: 'Comfy',
              labelEn: 'Comfy',
              emoji: '🛋️',
              quadrant: MoodQuadrant.green,
              pleasantness: 6,
              energy: 4,
              color: '#66BB6A',
              order: 43,
              aliases: ['comfy'],
            ),
            MoodDefinition(
              id: 'cozy',
              source: MoodSource.system,
              label: 'Cozy',
              labelEn: 'Cozy',
              emoji: '🕯️',
              quadrant: MoodQuadrant.green,
              pleasantness: 6,
              energy: 4,
              color: '#66BB6A',
              order: 44,
              aliases: ['cozy'],
            ),
            MoodDefinition(
              id: 'balanced',
              source: MoodSource.system,
              label: 'Balanced',
              labelEn: 'Balanced',
              emoji: '⚖️',
              quadrant: MoodQuadrant.green,
              pleasantness: 7,
              energy: 4,
              color: '#66BB6A',
              order: 45,
              aliases: ['balanced'],
            ),
            MoodDefinition(
              id: 'calm',
              source: MoodSource.system,
              label: 'Calm',
              labelEn: 'Calm',
              emoji: '🍃',
              quadrant: MoodQuadrant.green,
              pleasantness: 7,
              energy: 3,
              color: '#66BB6A',
              order: 46,
              aliases: ['calm'],
            ),
            MoodDefinition(
              id: 'relaxed',
              source: MoodSource.system,
              label: 'Relaxed',
              labelEn: 'Relaxed',
              emoji: '🧘',
              quadrant: MoodQuadrant.green,
              pleasantness: 7,
              energy: 3,
              color: '#66BB6A',
              order: 47,
              aliases: ['relaxed'],
            ),
            MoodDefinition(
              id: 'easygoing',
              source: MoodSource.system,
              label: 'Easygoing',
              labelEn: 'Easygoing',
              emoji: '😌',
              quadrant: MoodQuadrant.green,
              pleasantness: 7,
              energy: 3,
              color: '#66BB6A',
              order: 48,
              aliases: ['easygoing'],
            ),
            MoodDefinition(
              id: 'content',
              source: MoodSource.system,
              label: 'Content',
              labelEn: 'Content',
              emoji: '🙏',
              quadrant: MoodQuadrant.green,
              pleasantness: 7,
              energy: 3,
              color: '#66BB6A',
              order: 49,
              aliases: ['content'],
            ),
            MoodDefinition(
              id: 'carefree',
              source: MoodSource.system,
              label: 'Carefree',
              labelEn: 'Carefree',
              emoji: '🦋',
              quadrant: MoodQuadrant.green,
              pleasantness: 7,
              energy: 3,
              color: '#66BB6A',
              order: 50,
              aliases: ['carefree'],
            ),
            MoodDefinition(
              id: 'at_ease',
              source: MoodSource.system,
              label: 'At ease',
              labelEn: 'At ease',
              emoji: '🌤️',
              quadrant: MoodQuadrant.green,
              pleasantness: 8,
              energy: 2,
              color: '#66BB6A',
              order: 51,
              aliases: ['at_ease'],
            ),
            MoodDefinition(
              id: 'restful',
              source: MoodSource.system,
              label: 'Restful',
              labelEn: 'Restful',
              emoji: '😴',
              quadrant: MoodQuadrant.green,
              pleasantness: 8,
              energy: 2,
              color: '#66BB6A',
              order: 52,
              aliases: ['restful'],
            ),
            MoodDefinition(
              id: 'grateful',
              source: MoodSource.system,
              label: 'Grateful',
              labelEn: 'Grateful',
              emoji: '🙌',
              quadrant: MoodQuadrant.green,
              pleasantness: 8,
              energy: 2,
              color: '#66BB6A',
              order: 53,
              aliases: ['grateful'],
            ),
            MoodDefinition(
              id: 'satisfied',
              source: MoodSource.system,
              label: 'Satisfied',
              labelEn: 'Satisfied',
              emoji: '✅',
              quadrant: MoodQuadrant.green,
              pleasantness: 8,
              energy: 2,
              color: '#66BB6A',
              order: 54,
              aliases: ['satisfied'],
            ),
            MoodDefinition(
              id: 'secure',
              source: MoodSource.system,
              label: 'Secure',
              labelEn: 'Secure',
              emoji: '🏡',
              quadrant: MoodQuadrant.green,
              pleasantness: 8,
              energy: 2,
              color: '#66BB6A',
              order: 55,
              aliases: ['secure'],
            ),
            MoodDefinition(
              id: 'serene',
              source: MoodSource.system,
              label: 'Serene',
              labelEn: 'Serene',
              emoji: '🌊',
              quadrant: MoodQuadrant.green,
              pleasantness: 9,
              energy: 1,
              color: '#66BB6A',
              order: 56,
              aliases: ['serene'],
            ),
            MoodDefinition(
              id: 'peaceful',
              source: MoodSource.system,
              label: 'Peaceful',
              labelEn: 'Peaceful',
              emoji: '🕊️',
              quadrant: MoodQuadrant.green,
              pleasantness: 9,
              energy: 1,
              color: '#66BB6A',
              order: 57,
              aliases: ['peaceful'],
            ),
            MoodDefinition(
              id: 'tranquil',
              source: MoodSource.system,
              label: 'Tranquil',
              labelEn: 'Tranquil',
              emoji: '🌙',
              quadrant: MoodQuadrant.green,
              pleasantness: 9,
              energy: 1,
              color: '#66BB6A',
              order: 58,
              aliases: ['tranquil'],
            ),
            MoodDefinition(
              id: 'blessed',
              source: MoodSource.system,
              label: 'Blessed',
              labelEn: 'Blessed',
              emoji: '🌟',
              quadrant: MoodQuadrant.green,
              pleasantness: 9,
              energy: 1,
              color: '#66BB6A',
              order: 59,
              aliases: ['blessed'],
            ),
            MoodDefinition(
              id: 'loving',
              source: MoodSource.system,
              label: 'Loving',
              labelEn: 'Loving',
              emoji: '💗',
              quadrant: MoodQuadrant.green,
              pleasantness: 9,
              energy: 2,
              color: '#66BB6A',
              order: 60,
              aliases: ['loving'],
            ),
            // BLUE quadrant (20 moods) - low energy, unpleasant
            MoodDefinition(
              id: 'bored',
              source: MoodSource.system,
              label: 'Bored',
              labelEn: 'Bored',
              emoji: '😐',
              quadrant: MoodQuadrant.blue,
              pleasantness: 4,
              energy: 4,
              color: '#42A5F5',
              order: 61,
              aliases: ['bored'],
            ),
            MoodDefinition(
              id: 'tired',
              source: MoodSource.system,
              label: 'Tired',
              labelEn: 'Tired',
              emoji: '😪',
              quadrant: MoodQuadrant.blue,
              pleasantness: 4,
              energy: 4,
              color: '#42A5F5',
              order: 62,
              aliases: ['tired'],
            ),
            MoodDefinition(
              id: 'uneasy',
              source: MoodSource.system,
              label: 'Uneasy',
              labelEn: 'Uneasy',
              emoji: '😕',
              quadrant: MoodQuadrant.blue,
              pleasantness: 4,
              energy: 4,
              color: '#42A5F5',
              order: 63,
              aliases: ['uneasy'],
            ),
            MoodDefinition(
              id: 'disappointed',
              source: MoodSource.system,
              label: 'Disappointed',
              labelEn: 'Disappointed',
              emoji: '😞',
              quadrant: MoodQuadrant.blue,
              pleasantness: 4,
              energy: 4,
              color: '#42A5F5',
              order: 64,
              aliases: ['disappointed'],
            ),
            MoodDefinition(
              id: 'weary',
              source: MoodSource.system,
              label: 'Weary',
              labelEn: 'Weary',
              emoji: '🥱',
              quadrant: MoodQuadrant.blue,
              pleasantness: 4,
              energy: 4,
              color: '#42A5F5',
              order: 65,
              aliases: ['weary'],
            ),
            MoodDefinition(
              id: 'down',
              source: MoodSource.system,
              label: 'Down',
              labelEn: 'Down',
              emoji: '☁️',
              quadrant: MoodQuadrant.blue,
              pleasantness: 3,
              energy: 3,
              color: '#42A5F5',
              order: 66,
              aliases: ['down'],
            ),
            MoodDefinition(
              id: 'gloomy',
              source: MoodSource.system,
              label: 'Gloomy',
              labelEn: 'Gloomy',
              emoji: '🌧️',
              quadrant: MoodQuadrant.blue,
              pleasantness: 3,
              energy: 3,
              color: '#42A5F5',
              order: 67,
              aliases: ['gloomy'],
            ),
            MoodDefinition(
              id: 'discouraged',
              source: MoodSource.system,
              label: 'Discouraged',
              labelEn: 'Discouraged',
              emoji: '🚧',
              quadrant: MoodQuadrant.blue,
              pleasantness: 3,
              energy: 3,
              color: '#42A5F5',
              order: 68,
              aliases: ['discouraged'],
            ),
            MoodDefinition(
              id: 'lonely',
              source: MoodSource.system,
              label: 'Lonely',
              labelEn: 'Lonely',
              emoji: '🪑',
              quadrant: MoodQuadrant.blue,
              pleasantness: 3,
              energy: 3,
              color: '#42A5F5',
              order: 69,
              aliases: ['lonely'],
            ),
            MoodDefinition(
              id: 'exhausted',
              source: MoodSource.system,
              label: 'Exhausted',
              labelEn: 'Exhausted',
              emoji: '🔋',
              quadrant: MoodQuadrant.blue,
              pleasantness: 3,
              energy: 3,
              color: '#42A5F5',
              order: 70,
              aliases: ['exhausted'],
            ),
            MoodDefinition(
              id: 'sad',
              source: MoodSource.system,
              label: 'Sad',
              labelEn: 'Sad',
              emoji: '😢',
              quadrant: MoodQuadrant.blue,
              pleasantness: 2,
              energy: 2,
              color: '#42A5F5',
              order: 71,
              aliases: ['sad'],
            ),
            MoodDefinition(
              id: 'disheartened',
              source: MoodSource.system,
              label: 'Disheartened',
              labelEn: 'Disheartened',
              emoji: '💔',
              quadrant: MoodQuadrant.blue,
              pleasantness: 2,
              energy: 2,
              color: '#42A5F5',
              order: 72,
              aliases: ['disheartened'],
            ),
            MoodDefinition(
              id: 'drained',
              source: MoodSource.system,
              label: 'Drained',
              labelEn: 'Drained',
              emoji: '🕳️',
              quadrant: MoodQuadrant.blue,
              pleasantness: 2,
              energy: 2,
              color: '#42A5F5',
              order: 73,
              aliases: ['drained'],
            ),
            MoodDefinition(
              id: 'apathetic',
              source: MoodSource.system,
              label: 'Apathetic',
              labelEn: 'Apathetic',
              emoji: '🫥',
              quadrant: MoodQuadrant.blue,
              pleasantness: 2,
              energy: 2,
              color: '#42A5F5',
              order: 74,
              aliases: ['apathetic'],
            ),
            MoodDefinition(
              id: 'alienated',
              source: MoodSource.system,
              label: 'Alienated',
              labelEn: 'Alienated',
              emoji: '🚪',
              quadrant: MoodQuadrant.blue,
              pleasantness: 2,
              energy: 2,
              color: '#42A5F5',
              order: 75,
              aliases: ['alienated'],
            ),
            MoodDefinition(
              id: 'miserable',
              source: MoodSource.system,
              label: 'Miserable',
              labelEn: 'Miserable',
              emoji: '😩',
              quadrant: MoodQuadrant.blue,
              pleasantness: 1,
              energy: 1,
              color: '#42A5F5',
              order: 76,
              aliases: ['miserable'],
            ),
            MoodDefinition(
              id: 'depressed',
              source: MoodSource.system,
              label: 'Depressed',
              labelEn: 'Depressed',
              emoji: '🌑',
              quadrant: MoodQuadrant.blue,
              pleasantness: 1,
              energy: 1,
              color: '#42A5F5',
              order: 77,
              aliases: ['depressed'],
            ),
            MoodDefinition(
              id: 'hopeless',
              source: MoodSource.system,
              label: 'Hopeless',
              labelEn: 'Hopeless',
              emoji: '⛓️',
              quadrant: MoodQuadrant.blue,
              pleasantness: 1,
              energy: 1,
              color: '#42A5F5',
              order: 78,
              aliases: ['hopeless'],
            ),
            MoodDefinition(
              id: 'despondent',
              source: MoodSource.system,
              label: 'Despondent',
              labelEn: 'Despondent',
              emoji: '🥀',
              quadrant: MoodQuadrant.blue,
              pleasantness: 1,
              energy: 1,
              color: '#42A5F5',
              order: 79,
              aliases: ['despondent'],
            ),
            MoodDefinition(
              id: 'despair',
              source: MoodSource.system,
              label: 'Despair',
              labelEn: 'Despair',
              emoji: '🖤',
              quadrant: MoodQuadrant.blue,
              pleasantness: 0,
              energy: 0,
              color: '#42A5F5',
              order: 80,
              aliases: ['despair'],
            ),
          ]
          .map(
            (mood) =>
                mood.copyWith(description: _systemMoodDescriptions[mood.id]),
          )
          .toList();
}
